<?php
/**
 * This file is part of heros-utils.
 *
 * @contact  mondagroup_php@163.com
 *
 */
namespace Monda\Utils\Test\Util;

use Monda\Utils\Util\Env;
use PHPUnit\Framework\TestCase;

class EnvTest extends TestCase
{
    protected $env;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->env = new Env(__DIR__ . '/.env');
    }

    public function testGet()
    {
        $this->assertEquals(18, $this->env->get('age'));
        $this->assertEquals(null, $this->env->get('age1'));
        $this->assertEquals(10, $this->env->get('age2', 10));
        $this->assertTrue($this->env->get('debug'));
        $this->assertEquals('zhangshan', $this->env->get('name'));
    }
}
